from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import os
import subprocess
from datetime import datetime
import requests

router = APIRouter(prefix="/forge")

class FullForgeRequest(BaseModel):
    app_name: str
    repo_url: str

@router.post("/full-cycle")
def forge_full_cycle(req: FullForgeRequest):
    app_name = req.app_name.strip().replace(" ", "_")
    base_repo_url = req.repo_url.strip()
    base_path = f"./generated/{app_name}"

    token = os.getenv("GITHUB_PAT")
    github_user = "sivachandra422"  # Replace with your actual GitHub username
    if not token:
        raise HTTPException(status_code=500, detail="GITHUB_PAT environment variable not set.")

    # Check if repo exists via GitHub API
    repo_name = base_repo_url.split('/')[-1].replace(".git", "")
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}
    repo_check_url = f"https://api.github.com/repos/{github_user}/{repo_name}"
    repo_create_url = f"https://api.github.com/user/repos"

    repo_exists = requests.get(repo_check_url, headers=headers)
    if repo_exists.status_code == 404:
        create_payload = {
            "name": repo_name,
            "description": "Akshaya Flutter Autogenerated App",
            "private": False,
            "auto_init": False
        }
        create_response = requests.post(repo_create_url, headers=headers, json=create_payload)
        if create_response.status_code not in [201, 202]:
            raise HTTPException(status_code=500, detail=f"GitHub repo creation failed: {create_response.text}")

    # Replace HTTPS with token-injected URL
    if base_repo_url.startswith("https://"):
        secure_repo_url = base_repo_url.replace("https://", f"https://{token}@")
    else:
        secure_repo_url = f"https://{token}@{base_repo_url}"

    try:
        os.makedirs(f"{base_path}/lib/screens", exist_ok=True)

        with open(f"{base_path}/pubspec.yaml", "w") as f:
            f.write(f"name: {app_name}\nversion: 1.0.0+1\ndependencies:\n  flutter:\n    sdk: flutter")

        with open(f"{base_path}/lib/main.dart", "w") as f:
            f.write("""import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Akshaya Dream App',
      home: HomeScreen(),
    );
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Akshaya Dream App')),
      body: Center(child: Text('Akshaya has generated this app.')),
    );
  }
}
""")

        with open(f"{base_path}/lib/screens/home.dart", "w") as f:
            f.write("// HomeScreen widget is defined in main.dart")

        if not os.path.exists(os.path.join(base_path, ".git")):
            subprocess.run(["git", "init"], cwd=base_path, check=True)
            subprocess.run(["git", "checkout", "-b", "main"], cwd=base_path, check=True)
            subprocess.run(["git", "remote", "add", "origin", secure_repo_url], cwd=base_path, check=True)

        subprocess.run(["git", "config", "user.email", "akshaya@yourdomain.com"], cwd=base_path, check=True)
        subprocess.run(["git", "config", "user.name", "Akshaya Forge"], cwd=base_path, check=True)

        subprocess.run(["git", "add", "."], cwd=base_path, check=True)

        try:
            subprocess.run(["git", "commit", "-m", f"Akshaya Full-Cycle {datetime.utcnow().isoformat()}"], cwd=base_path, check=True)
        except subprocess.CalledProcessError:
            raise HTTPException(status_code=400, detail="Nothing to commit. Repo might already be up to date.")

        result = subprocess.run(
            ["git", "push", "-u", "origin", "main", "--force"],
            cwd=base_path,
            capture_output=True,
            text=True
        )
        if result.returncode != 0:
            raise HTTPException(status_code=500, detail=result.stderr)

        return {
            "status": "success",
            "message": f"{app_name} generated and pushed to GitHub.",
            "timestamp": datetime.utcnow().isoformat(),
            "repo": base_repo_url
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))